config/routes.rb
Rails.application.routes.draw do

  match "/404" => "errors#four_oh_four", via: [ :get, :post, :patch, :delete ]

  devise_for :users, :path => "", :path_names => {:sign_in => "login", :sign_out => "logout"}

  namespace :admin do
    get '/' => 'dashboard#index'
    resources :users
    resources :releases
    resources :artists
    resources :mixes
    resources :events
  end

  resources :users

  resources :events
  resources :performances

  get 'coolroom/episode/:id' => 'events#show'
  get 'coolroom' => 'events#index'
  
  resources :artists do
    resources :releases
  end

  get 'releases/:id/:secret' => 'releases#show'
  get 'mixes/:id/:secret' => 'mixes#show'

  resources :releases
  resources :mixes

  get 'contact' => 'contact#index'
  get 'privacy' => 'home#privacy'
  get 'legal' => 'home#legal'
  get 'about' => 'home#about'
  root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId

  has_many :performances
  has_many :artists, through: :performances do
    def featured
     where("performances.featured = ?", true)
    end
  end

  accepts_nested_attributes_for :artists, :reject_if => :all_blank, :allow_destroy => true

  friendly_id :slug, use: :slugged
  validates :slug, presence: true, uniqueness: true

  acts_as_opengraph :values => { :type => "event"}

  # To have published and unpublished releases
  # http://stackoverflow.com/questions/16788273/rails-displaying-published-post-by-all-and-unpublished-post-of-current-user
  scope :published, -> { where(published: true).order('start_date desc') }
  scope :season_one, -> { where("id <= ?", 6).where(published: true).order('start_date desc') }
  scope :season_two, -> { where("id > ?", 6).where("id <= ?", 15).where(published: true).order('start_date desc') }
  scope :season_three, -> { where("id > ?", 15).where(published: true).order('start_date desc') }
  scope :upcoming, -> { where(published: true).where("start_date > ?", Date.today - 1).order('start_date desc') }
  scope :un_published, -> { where(published: false) }

  default_scope { order('start_date desc') }

  def opengraph_image
    facebook_image.facebook.url
  end

  mount_uploader :cover, BannerUploader
  crop_uploaded :cover

  mount_uploader :facebook_image, BannerUploader
  crop_uploaded :facebook_image

  mount_uploader :trailer, BannerUploader
  crop_uploaded :trailer

  def url
    if self.cool_room?
      return "coolroom/episode/#{self.slug}"
    else
      return "events/#{self.slug}"
    end
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController
  # before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.order(:start_date)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @event = Event.friendly.find(params[:id])

    if(@event.secret_hash.blank?)
      @event.secret_hash = SecureRandom.hex(4)
      #@event.save
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.secret_hash = SecureRandom.hex(4)

    respond_to do |format|
      if @event.save
        format.html {
          redirect_to edit_admin_event_path(@event), notice: 'The event was successfully created.'
        }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event = Event.friendly.find(params[:id])

    respond_to do |format|
      if @event.update(event_params)
        format.html {
          redirect_to edit_admin_event_path(@event), notice: 'The event was successfully updated.' 
        }
        format.json { render action: 'show', status: :updated, location: @event }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # # Use callbacks to share common setup or constraints between actions.
    # def set_event
    #   @event = Event.friendly.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params
      .require(:event)
      .permit(:event_no, :slug, :title, :lead, :description, :facebook_page, :facebook_event, :call_to_action_url, :call_to_action_text, :manifesto, :livestream, :start_date, :finish_date, :location, :cover, :trailer, :facebook_image, :published, :cool_room, :thanks_header, :thanks_text, :completed, :artist_id, :soundcloud_embed, :cover_crop_x, :cover_crop_y, :cover_crop_w, :cover_crop_h, :trailer_crop_x, :trailer_crop_y, :trailer_crop_w, :trailer_crop_h)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @season_one_events = Event.season_one
    @season_two_events = Event.season_two
    @season_three_events = Event.season_three
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.includes(:artists => :performances).friendly.find(params[:id])

    if @event.published == false
      if params[:secret] != @event.secret_hash
        raise ActionController::RoutingError.new('Not Found')
      end
    end

    @event_upcoming = Time.zone.now < @event.start_date;
    @event_live = Time.zone.now >= @event.start_date && Time.zone.now < @event.finish_date
    @event_already_happened = @event.finish_date < Time.zone.now;
    @event_finished = @event_already_happened && @event.completed;
  end
end

app/views/admin/events/_artist.html.erb
<h3><%= artist.name %></h3>
<div class="form-group">
  <%= f.label :audio_url %>
  <%= f.text_field :audio_url, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :audio_embed %>
  <%= f.text_area :audio_embed, cols: 5, rows: 3, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :video_url %>
  <%= f.text_field :video_url, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :video_embed %>
  <%= f.text_area :video_embed, cols: 5, rows: 3, class: "form-control" %>
</div>

app/views/admin/events/_form.html.erb
<%= form_for(@event, url: url, html: { role: "form" } ) do |f| %>
  <div class="form-group">
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@event.errors.count, "error") %> prohibited
          this event from being saved:</h2>
        <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

     <div class="form-group">
      <%= f.label :slug %>
      <%= f.text_field :slug, class: "form-control" %>
       <p class="help-block">Based off the title</p>
    </div>

    <div class="form-group">
      <%= f.label :cover %>

      <div>
        <%= image_tag(@event.cover.url) %>
      </div>

       <%= f.file_field :cover %>

      <p class="help-block">Upload an image please. This is required.</p>
    </div>

    <div class="form-group">
      <%= f.label :trailer %>

      <div>
        <%= image_tag(@event.trailer.url) %>
      </div>

       <%= f.file_field :trailer %>

      <p class="help-block">Upload an image please. This is required.</p>
    </div>

     <div class="form-group">
      <%= f.label :facebook_image %>

      <div>
        <%= image_tag(@event.facebook_image.url) %>
      </div>

       <%= f.file_field :facebook_image %>

      <p class="help-block">Upload an image please. This is required.</p>
    </div>

    <div class="form-group">
      <%= f.label :facebook_event %>
      <%= f.text_field :facebook_event, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :facebook_page %>
      <%= f.text_field :facebook_page, class: "form-control" %>
    </div>

     <div class="form-group">
      <%= f.label :call_to_action_url %>
      <%= f.text_field :call_to_action_url, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :call_to_action_text %>
      <%= f.text_field :call_to_action_text, class: "form-control" %>
    </div>

     <div class="form-group">
      <%= f.label :start_date %>
      <%= f.text_field :start_date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :finish_date %>
      <%= f.text_field :finish_date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :location %>
      <%= f.text_field :location, class: "form-control" %>
    </div>

   <div class="form-group">
      <%= f.label :lead %>
      <%= f.text_area :lead, cols: 5, rows: 3, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, cols: 5, rows: 10, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :livestream %>
      <%= f.text_area :livestream, cols: 5, rows: 3, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :thanks_header %>
      <%= f.text_field :thanks_header, class: "form-control" %>
    </div>

   <div class="form-group">
      <%= f.label :thanks_text %>
      <%= f.text_area :thanks_text, cols: 5, rows: 3, class: "form-control" %>
    </div>

<!--     <div class="form-group">
      <%= f.label :artists %>
      <br>
      <%= f.collection_select(:artist_ids, Artist.all, :id, :name, {prompt: "Please select", selected: @event.artist_ids, include_blank: true}, {class: "form-control chosen-select", multiple: true}) %>
    </div>
 -->
    <div class="form-group">
      <%= f.label :published %>
      <%= f.check_box :published, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :completed %>
      <%= f.check_box :completed, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :cool_room %>
      <%= f.check_box :cool_room, class: "form-control" %>
    </div>

    <%= button_tag(type: 'submit', class: "btn btn-lg btn-primary") do %>
      Save
    <% end %>
    <%= link_to 'Delete', url,
      method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
  </div>
<% end %>

app/views/admin/events/crop.html.erb
<h1>Crop That Image</h1>

<%= form_for(@event, url: admin_event_path, html: { role: "form" } ) do |f| %>
  <div class="form-group">
    <div class="form-group">
      <%= f.cropbox :cover %>
    </div>

    <div class="form-group">
      <%= f.previewbox :cover %>
    </div>

    <div class="form-group">
      <%= button_tag(type: 'submit', class: "btn btn-lg btn-primary") do %>
        Crop
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<h1>Editing Event</h1>

<div class="well">
  <%= link_to 'View Promo Version', event_path(@event), class: "btn btn-primary" %>
  <code>
    http://jusbchill.com<%= url_for(@event) + "/" + @event.secret_hash %>
  </code>
</div>

<%= render partial: 'form', locals: {url: admin_event_path(@event)} %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/admin/events/index.html.erb
<h1>Events
  <%= link_to 'New Event', new_admin_event_path, class: "btn btn-primary btn-new-release pull-right" %>
</h1>

<section class="card row">
  <% @events.each do |event| %>
    <div class="card col-md-4">
      <div class="card-image">
        <%= link_to(edit_admin_event_path(event), {}) do %>
          <%= image_tag(event.cover.jumbo.url) %>
        <% end %>
      </div>
      <div class="card-details">
        <h4><%= event.slug %></h4>
        <h4><%= event.title %></h4>
      </div>
    </div>
  <% end %>
</section>

app/views/admin/events/new.html.erb
<h1>New Event</h1>

<%= render partial: 'form', locals: {url: admin_events_path} %>

<%= link_to 'Back', admin_events_path %>